### ISSUE TITLE
validation gives an unexpected error

### ISSUE THREAD

**Issue by Mikanebu** [datopian/data-cli#129]
When I run validation for this package `https://github.com/datasets/ICC-Incoterms`, it gives me the following error: 
```bash
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: Invalid opening quote at line 2
    at Parser.__write (/Users/Zhiyenbayev_mirza/Desktop/Datopian/src/core-datasets-tools/node_modules/csv-parse/lib/index.js:422:16)
    at Parser._transform (/Users/Zhiyenbayev_mirza/Desktop/Datopian/src/core-datasets-tools/node_modules/csv-parse/lib/index.js:182:14)
    at Parser.Transform._read (_stream_transform.js:190:10)
    at Parser.Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:371:12)
    at writeOrBuffer (_stream_writable.js:357:5)
    at Parser.Writable.write (_stream_writable.js:274:11)
    at ReadStream.ondata (_stream_readable.js:628:20)
    at emitOne (events.js:115:13)
    at ReadStream.emit (events.js:210:7)
```
Another package un-locode `https://github.com/datasets/un-locode` with the error: 
```bash
(node:6361) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 16 end listeners added. Use emitter.setMaxListeners() to increase limit
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: Invalid closing quote at line 70547; found "E" instead of delimiter ","
    at Parser.__write (/Users/Zhiyenbayev_mirza/Desktop/Datopian/src/core-datasets-tools/node_modules/csv-parse/lib/index.js:405:20)
    at Parser._transform (/Users/Zhiyenbayev_mirza/Desktop/Datopian/src/core-datasets-tools/node_modules/csv-parse/lib/index.js:182:14)
    at Parser.Transform._read (_stream_transform.js:190:10)
    at Parser.Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:371:12)
    at writeOrBuffer (_stream_writable.js:357:5)
    at Parser.Writable.write (_stream_writable.js:274:11)
    at ReadStream.ondata (_stream_readable.js:628:20)
    at emitOne (events.js:115:13)
    at ReadStream.emit (events.js:210:7)
```

**Comment by anuveyatsu** [comment]
@Mikanebu https://github.com/datasets/ICC-Incoterms is fixed in https://github.com/frictionlessdata/tableschema-js/pull/81

Re https://github.com/datasets/un-locode I am not sure but think there is a bug in `csv` library so I have opened an issue there: https://github.com/wdavidw/node-csv-parse/issues/143

In general, I will also handle these sort of errors so when we do validation of multiple data packages it wouldn't stop/crash.

**Comment by anuveyatsu** [comment]
**UPDATE**
https://github.com/datasets/ICC-Incoterms is fixed now via https://github.com/frictionlessdata/tableschema-js/pull/81

**Comment by anuveyatsu** [comment]
@Mikanebu can you take a look at my comment below and fix that upstream (open an issue if necessary) - https://github.com/wdavidw/node-csv-parse/issues/143#issuecomment-320497006

**Comment by Mikanebu** [comment]
@anuveyatsu It is fixed now, https://github.com/datasets/un-locode/issues/14

**Comment by Mikanebu** [comment]
FIXED
