### ISSUE TITLE
data command does not work after npm install -g

### ISSUE THREAD

**Issue by zelima** [datopian/data-cli#139]
Node - 8.0.0 

after running `npm install -g` it gets installed but running `data` results:
Note: everything works fine if I do `npm link`
```
module.js:487
    throw err;
    ^

Error: Cannot find module 'babel-core/register'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/zelima/datopian/datahq/datahub-cli/bin/data.js:4:1)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```

**Comment by anuveyatsu** [comment]
INVALID. We now don't use Babel so this should work.
