### ISSUE TITLE
[cat] QA review 8 Aug 2017

### ISSUE THREAD

**Issue by zelima** [datopian/data-cli#141]
A. `data cat not_exists` noisy error:

```
(node:18812) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: We do not have a parser for that format: 
(node:18812) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

B. `data cat not_exists.csv` noisy Unhandled promise rejection error:

```
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'not_exists.csv'
```

C. `data cat https://example.com/example.csv` noisy noisy Unhandled promise rejection error: error

```
(node:19285) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Invalid opening quote at line 6
(node:19285) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

D. `data cat invalid.csv` - same noisy error

E. `data cat sample.xlsx 2` - (idea - "show me second sheet") errors

```
path.js:28
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received 2
    at assertPath (path.js:28:11)
    at Object.extname (path.js:1452:5)
    at Object.<anonymous> (/home/zelima/datopian/datahq/datahub-cli/bin/data-cat.js:33:2)
    at Module._compile (module.js:569:30)
    at loader (/home/zelima/datopian/datahq/datahub-cli/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/zelima/datopian/datahq/datahub-cli/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
```

F. data cat with url without clear extension throws error

## Acceptance criteria

* [x] we are handling all uncaught exceptions and unhandled rejections

## Tasks

* [x] handle all uncaught exceptions and unhandled rejections in the top level - `/bin/data.js`

## Analysis

In `/bin/data.js`:

```javascript
const {handleError} = require('../lib/utils/error')

// Handle all uncaught exceptions and unhandled rejections
process.on('uncaughtException', (err) => {
  handleError(err)
})

process.on('unhandledRejection', (err) => {
  handleError(err)
})
```

**Comment by rufuspollock** [comment]
General comment that Resource failing to open due to 404 / non existent file should be handled better at top level in some way ... -- this is probably a common issue in several commands.

**Comment by anuveyatsu** [comment]
FIXED. Now handling uncaught exceptions & unhandled rejections in the top level `/bin/data.js`
