### ISSUE TITLE
data push fails I get dataset from datahub.io

### ISSUE THREAD

**Issue by zelima** [datopian/data-cli#180]
If you get a dataset from datahub and re-push, it fails with `> Error! Error: Response error - no information. Status code: 400 - BAD REQUEST`

## Acceptance criteria

* [ ] able to get dataset from datahub.io, modify (Eg: remove some rows) and republish 

## Analysis 

Reproduce:
1. push package on datahub.io - `data push myUsername/my-package`
2. now get back package - `data get https://datahub.io/myUsername/my-package`
3. push again - `data push myUsername/my-package`

Log from debug mode:
```
⠋ Commencing push ...> [debug] Getting rawstore upload creds
> [debug] Getting authz token for rawstore service
⠦ Commencing push ...> [debug] Calling rawstore authorize with
> [debug] {
  "metadata": {
    "owner": "0e9b59cd50f1884058c1aa242d71a228"
  },
  "filedata": {
    "vix-daily": {
      "name": "vix-daily"
    },
    "vix-daily_csv": {
      "name": "vix-daily_csv"
    },
    "vix-daily_csv_preview": {
      "name": "vix-daily_csv_preview"
    },
    "vix-daily_json": {
      "name": "vix-daily_json"
    },
    "datapackage.json": {
      "length": 6400,
      "md5": "UW40BMOEGoG63i+Kzr+TzA==",
      "name": "datapackage.json"
    }
  }
}
> Error! Error: Response error - no information. Status code: 400 - BAD REQUEST
> [debug]
Error: Error: Response error - no information. Status code: 400 - BAD REQUEST
    at DataHub.rawstoreAuthorize (/home/zelima/datopian/datahq/datahub-cli/lib/utils/datahub.js:146:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
```

**Comment by zelima** [comment]
FIXED. This is no more an issue able to push. Though it has some validation errors https://datahub.io/zelima/sample-quick-cobra-16/v/2
